### ISSUE TITLE
Account is not stored

### ISSUE THREAD

**Issue by Mikaela** [flathub/org.briarproject.Briar#5]
Every time I open Briar I am asked to create a nickname and password. When I close Briar and open it again, I get the same screen and everything is lost.

Terminal doesn't show anything helpful

```
20:08:53.968 [main] INFO  org.briarproject.briar.desktop.Main - This is briar-desktop version 0.2.0-beta
20:08:53.971 [main] INFO  org.briarproject.briar.desktop.Main - Build info:
20:08:53.971 [main] INFO  org.briarproject.briar.desktop.Main -   Git hash 22ef2f33880e9ecae8c8456655daa06b3d2eaf3b
20:08:53.972 [main] INFO  org.briarproject.briar.desktop.Main -   Commit time 2022-02-22 16:54:54
20:08:53.973 [main] INFO  org.briarproject.briar.desktop.Main -   Branch <unknown>
Cannot create Linux GL context
20:09:33.279 [pool-3-thread-1] INFO  o.b.b.d.l.RegistrationSubViewModel - Created account
```

after restart

```
20:09:48.954 [main] INFO  org.briarproject.briar.desktop.Main - This is briar-desktop version 0.2.0-beta
20:09:48.959 [main] INFO  org.briarproject.briar.desktop.Main - Build info:
20:09:48.960 [main] INFO  org.briarproject.briar.desktop.Main -   Git hash 22ef2f33880e9ecae8c8456655daa06b3d2eaf3b
20:09:48.960 [main] INFO  org.briarproject.briar.desktop.Main -   Commit time 2022-02-22 16:54:54
20:09:48.961 [main] INFO  org.briarproject.briar.desktop.Main -   Branch <unknown>
Cannot create Linux GL context
```

I don't know if this is the correct place to report this and I understand the Flatpak isn't fully supported yet. Judging by the terminal output the build is almost a month old and on Matrix I got the impression that Briar should support the `--help` flag which the flatpak doesn't recognise (just opening Briar normally), so I think it may be somewhat outdated.

**Comment by Mikaela** [comment]
The proper solution may be [using xdg directories on briar-desktop side](https://code.briarproject.org/briar/briar-desktop/-/issues/257)

**Comment by sebkur** [comment]
At the moment briar-desktop is using `~/.briar/desktop` for storing the account

**Comment by sebkur** [comment]
and the unencrypted settings that don't go into the account database (light/dark theme, language) are stored in `~/.java/.userPrefs/org/briarproject/briar/desktop/settings/prefs.xml` which is rather weird location, but it is what `java.util.prefs.Preferences` uses as a default for our application package. See https://code.briarproject.org/briar/briar-desktop/-/merge_requests/140#note_62323 for a discussion.

**Comment by Mikaela** [comment]
Thanks, I was wondering why dark/light theme didn't work and added it to the workaround PR #6, while all this feels wrong 🙈

**Comment by barthalion** [comment]
I pushed two commits that should fix these issues (and one more I've had with displaying the window contents at all).
